version: "3.9"
services:
  postgres:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: password
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DATABASE_URL: "postgresql://postgres_user:password@postgres/sports-broadcast-store-dc"
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    working_dir: /app/frontend
    volumes:
      - ./client:/app/frontend
    ports:
      - "3005:3005"
    depends_on:
      - backend

