FROM ruby:2.7.2
# less is required for Pry
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client less
WORKDIR /app

ENV RAILS_ENV development

# install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# remove any old JS assets and copy new ones over
RUN rm -f public/index.html
RUN rm -rf public/static

# copy in rest of source code
COPY . /app/

EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "--port", "3000", "--binding", "0.0.0.0"]
